version: '3.7'

services:

  web:
    container_name: ${PROJECT_NAME}_web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - './web:/app/web'
      - /app/web/node_modules
    ports:
      - '4000:4000'

  api:
    container_name: ${PROJECT_NAME}_api
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - ./api:/app/api
    ports:
      - "3000:3000"
    depends_on:
        - db
        - redis

  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:11
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  db:
    driver: local
  redis:
    driver: local
