version: '3.7'

services:

  web:
    container_name: ${PROJECT_NAME}_web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - './web:/app/web'
      - /app/web/node_modules
    ports:
      - '1100:1100'

  api:
    container_name: ${PROJECT_NAME}_api
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - ./api:/app/api
    ports:
      - "1000:1000"
    depends_on:
        - db

  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:11
    ports:
      - "1300:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
