export { default as Home } from './Home/index.vue'
export { default as Login } from './Login/index.vue'
// export { default as Order } from './Order/index.vue'
// export { default as MenuComponent } from './MenuComponent/index.vue'
// export { default as Setting } from './Setting/index.vue'
